version: "3.8"

services:

  backend:
    build: ./backend
    container_name: telegram-backend
    env_file:
      - .env
    volumes:
      - ./backend/session_data:/app/session_data
      - ./backend/uploads:/app/uploads
    ports:
      - "1993:1993"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: telegram-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped