version: "3.8"

services:

  backend:
    build: ./backend
    container_name: telegram-backend
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - PORT=1993
      - CORS_ORIGIN=*
      - LD_LIBRARY_PATH=/app/tdlib 
    volumes:
      - ./backend/session_data:/app/session_data
      - ./backend/uploads:/app/uploads
      - ./backend/tdlib:/app/tdlib:ro
    ports:
      - "1993:1993"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: telegram-frontend
    ports:
      - "1989:80"
    depends_on:
      - backend
    restart: unless-stopped